# Generated by Django 3.1.7 on 2021-03-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('generated_url', models.CharField(default='7su18i9qRh8', max_length=11, unique=True)),
                ('self_destruct', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expired_date', models.DateTimeField()),
            ],
        ),
    ]
