# Generated by Django 3.1.7 on 2021-03-13 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='post',
            name='expired_date',
        ),
        migrations.AddField(
            model_name='post',
            name='expires_on',
            field=models.DateTimeField(choices=[('10 Mins', datetime.datetime(2021, 3, 13, 21, 18, 39, 653256)), ('1 hour', datetime.datetime(2021, 3, 13, 22, 8, 39, 653313)), ('2 hour', datetime.datetime(2021, 3, 13, 23, 8, 39, 653329)), ('1 Week', datetime.datetime(2021, 3, 20, 21, 8, 39, 653341)), ('2 Weeks', datetime.datetime(2021, 3, 27, 21, 8, 39, 653352)), ('1 Month', datetime.datetime(2021, 4, 13, 21, 8, 39, 653362)), ('6 Months', datetime.datetime(2021, 9, 13, 21, 8, 39, 653373)), ('1 year', datetime.datetime(2022, 3, 13, 21, 8, 39, 653383))], null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='generated_url',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
