# Generated by Django 3.1.7 on 2021-03-13 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_app', '0002_auto_20210313_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='self_destruct',
        ),
        migrations.AlterField(
            model_name='post',
            name='expires_on',
            field=models.DateTimeField(choices=[(None, 'Never'), (datetime.datetime(2021, 3, 13, 21, 27, 10, 796221), '10 Mins'), (datetime.datetime(2021, 3, 13, 22, 17, 10, 796277), '1 hour'), (datetime.datetime(2021, 3, 13, 23, 17, 10, 796293), '2 hour'), (datetime.datetime(2021, 3, 20, 21, 17, 10, 796305), '1 Week'), (datetime.datetime(2021, 3, 27, 21, 17, 10, 796316), '2 Weeks'), (datetime.datetime(2021, 4, 13, 21, 17, 10, 796326), '1 Month'), (datetime.datetime(2021, 9, 13, 21, 17, 10, 796337), '6 Months'), (datetime.datetime(2022, 3, 13, 21, 17, 10, 796347), '1 year')], null=True),
        ),
    ]
