# Generated by Django 3.1.7 on 2021-03-13 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_app', '0003_auto_20210313_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_on',
            field=models.DurationField(choices=[(None, 'Never'), (datetime.datetime(2021, 3, 13, 22, 5, 2, 631246), '10 Mins'), (datetime.datetime(2021, 3, 13, 22, 55, 2, 631298), '1 hour'), (datetime.datetime(2021, 3, 13, 23, 55, 2, 631314), '2 hour'), (datetime.datetime(2021, 3, 20, 21, 55, 2, 631325), '1 Week'), (datetime.datetime(2021, 3, 27, 21, 55, 2, 631336), '2 Weeks'), (datetime.datetime(2021, 4, 13, 21, 55, 2, 631346), '1 Month'), (datetime.datetime(2021, 9, 13, 21, 55, 2, 631356), '6 Months'), (datetime.datetime(2022, 3, 13, 21, 55, 2, 631366), '1 year')], null=True),
        ),
    ]
