# Generated by Django 3.1.7 on 2021-03-13 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_app', '0004_auto_20210313_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_on',
            field=models.DateTimeField(choices=[(None, 'Never'), (datetime.datetime(2021, 3, 13, 22, 8, 13, 137072), '10 Mins'), (datetime.datetime(2021, 3, 13, 22, 58, 13, 137120), '1 hour'), (datetime.datetime(2021, 3, 13, 23, 58, 13, 137135), '2 hour'), (datetime.datetime(2021, 3, 20, 21, 58, 13, 137146), '1 Week'), (datetime.datetime(2021, 3, 27, 21, 58, 13, 137157), '2 Weeks'), (datetime.datetime(2021, 4, 13, 21, 58, 13, 137167), '1 Month'), (datetime.datetime(2021, 9, 13, 21, 58, 13, 137178), '6 Months'), (datetime.datetime(2022, 3, 13, 21, 58, 13, 137188), '1 year')], null=True),
        ),
    ]
