# Generated by Django 3.1.7 on 2021-03-13 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_app', '0005_auto_20210313_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_on',
            field=models.DateTimeField(choices=[(None, 'Never'), (datetime.datetime(2021, 3, 13, 22, 49, 41, 880422), '10 Mins'), (datetime.datetime(2021, 3, 13, 23, 39, 41, 880491), '1 hour'), (datetime.datetime(2021, 3, 14, 0, 39, 41, 880509), '2 hour'), (datetime.datetime(2021, 3, 20, 22, 39, 41, 880522), '1 Week'), (datetime.datetime(2021, 3, 27, 22, 39, 41, 880534), '2 Weeks'), (datetime.datetime(2021, 4, 13, 22, 39, 41, 880545), '1 Month'), (datetime.datetime(2021, 9, 13, 22, 39, 41, 880557), '6 Months'), (datetime.datetime(2022, 3, 13, 22, 39, 41, 880568), '1 year')], null=True),
        ),
    ]
