# Generated by Django 3.1.7 on 2021-03-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_app', '0006_auto_20210313_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_on',
            field=models.CharField(choices=[(None, 'Never'), ('2021-03-13 22:51:43.503797', '10 Mins'), ('2021-03-13 23:41:43.503880', '1 hour'), ('2021-03-14 00:41:43.503904', '2 hour'), ('2021-03-20 22:41:43.503922', '1 Week'), ('2021-03-27 22:41:43.503939', '2 Weeks'), ('2021-04-13 22:41:43.503955', '1 Month'), ('2021-09-13 22:41:43.503971', '6 Months'), ('2022-03-13 22:41:43.503987', '1 year')], max_length=26, null=True),
        ),
    ]
