# Generated by Django 3.1.7 on 2021-03-13 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_app', '0007_auto_20210313_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expires_on_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='expires_on',
            field=models.CharField(choices=[(None, 'Never'), ('2021-03-13 23:47:56.851246', '1 Mins'), ('2021-03-13 23:56:56.851340', '10 Mins'), ('2021-03-14 00:46:56.851365', '1 hour'), ('2021-03-14 01:46:56.851386', '2 hour'), ('2021-03-20 23:46:56.851404', '1 Week'), ('2021-03-27 23:46:56.851421', '2 Weeks'), ('2021-04-13 23:46:56.851438', '1 Month'), ('2021-09-13 23:46:56.851456', '6 Months'), ('2022-03-13 23:46:56.851472', '1 year')], max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='generated_url',
            field=models.CharField(editable=False, max_length=11, unique=True),
        ),
    ]
