# Generated by Django 3.1.7 on 2021-03-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_app', '0008_auto_20210313_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_on',
            field=models.CharField(choices=[(None, 'Never'), ('2021-03-14 00:16:08.978844', '1 Mins'), ('2021-03-14 00:25:08.978973', '10 Mins'), ('2021-03-14 01:15:08.979008', '1 hour'), ('2021-03-14 02:15:08.979036', '2 hour'), ('2021-03-21 00:15:08.979060', '1 Week'), ('2021-03-28 00:15:08.979084', '2 Weeks'), ('2021-04-14 00:15:08.979107', '1 Month'), ('2021-09-14 00:15:08.979131', '6 Months'), ('2022-03-14 00:15:08.979155', '1 year')], max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='expires_on_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
